services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: inventradb
      DB_USER: inventra
      DB_PASSWORD: inventrapass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventradb
      POSTGRES_USER: inventra
      POSTGRES_PASSWORD: inventrapass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventra -d inventradb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
